# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Meesum Ali
email: meesumdex@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Software Engineer and Educator specializing in System Thinking, Lean Development, 
  and Organizational Improvement. Sharing insights on software engineering best practices.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://meesum-ali.github.io"
author: Meesum Ali
twitter_username: meesum1992
github_username: meesum-ali
linkedin_username: smeesumali

# Favicon settings
favicon:
  source: /assets/images/favicon.ico
  fallback_text: MA

# SEO settings
twitter:
  username: meesum1992
  card: summary
social:
  name: Meesum Ali
  links:
    - https://twitter.com/meesum1992
    - https://www.linkedin.com/in/smeesumali
    - https://github.com/meesum-ali

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Show future dated posts
future: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
